-- Consulta SEDAP+ executada em 2026-09-23 17:59:12 (horario de Brasilia)
-- Produz: data/matriz_2020_fina_ead.csv
-- epsilon = 1, delta = 1e-06; linhas devolvidas = 204; row_loss (fracao de celulas suprimidas) = 0
-- Texto exato enviado a API, copiado do log de consultas.
/*+ epsilon=1, delta=1e-06 */
WITH concluintes AS (
    SELECT CPF_MASC
    FROM raw.BAS_MATRICULA_2020
    WHERE CAST(TP_ETAPA_ENSINO AS STRING) IN ('27', '28', '29', '32', '33', '34', '37', '38')
      AND CAST(NU_IDADE AS INT64) >= 16
      AND CAST(NU_IDADE AS INT64) <= 22
      AND CPF_MASC IS NOT NULL
    GROUP BY CPF_MASC
),
enem AS (
    SELECT CPF_MASC,
           CAST(Q006 AS STRING) AS FAIXA_RENDA,
           SAFE_CAST(Q005 AS INT64) AS MORADORES
    FROM raw.ENEM_2020_SEDAP
    WHERE CPF_MASC IS NOT NULL
      AND Q006 IS NOT NULL
    GROUP BY CPF_MASC, Q006, Q005
),
ingresso_linhas AS (
        SELECT CPF_MASC, CASE WHEN CAST(TP_MODALIDADE_ENSINO AS STRING) = '2' THEN 1 ELSE 2 END AS COD_MODALIDADE FROM raw.SUP_ALUNO_2021 WHERE CAST(NU_ANO_INGRESSO AS STRING) IN ('2021') AND CPF_MASC IS NOT NULL
        UNION ALL
        SELECT CPF_MASC, CASE WHEN CAST(TP_MODALIDADE_ENSINO AS STRING) = '2' THEN 1 ELSE 2 END AS COD_MODALIDADE FROM raw.SUP_ALUNO_2022 WHERE CAST(NU_ANO_INGRESSO AS STRING) IN ('2021', '2022') AND CPF_MASC IS NOT NULL
        UNION ALL
        SELECT CPF_MASC, CASE WHEN CAST(TP_MODALIDADE_ENSINO AS STRING) = '2' THEN 1 ELSE 2 END AS COD_MODALIDADE FROM raw.SUP_ALUNO_2023 WHERE CAST(NU_ANO_INGRESSO AS STRING) IN ('2021', '2022', '2023') AND CPF_MASC IS NOT NULL
),
ingresso AS (
    SELECT CPF_MASC, MIN(COD_MODALIDADE) AS COD_MODALIDADE
    FROM ingresso_linhas
    GROUP BY CPF_MASC
)
SELECT
    e.FAIXA_RENDA,
    CASE WHEN e.MORADORES IS NULL THEN 'desconhecido'
         WHEN e.MORADORES <= 2 THEN '1_2'
         WHEN e.MORADORES <= 4 THEN '3_4'
         WHEN e.MORADORES <= 6 THEN '5_6'
         ELSE '7_mais' END AS MORADORES_GRUPO,
    IFNULL(s.COD_MODALIDADE, 0) AS COD_MODALIDADE,
    COUNT(*) AS N
FROM concluintes c
INNER JOIN enem e ON c.CPF_MASC = e.CPF_MASC
LEFT JOIN ingresso s ON c.CPF_MASC = s.CPF_MASC
GROUP BY e.FAIXA_RENDA, MORADORES_GRUPO, COD_MODALIDADE
